### ISSUE TITLE
frontend developer

### ISSUE THREAD

**Issue by SteMak** [near/metabuidl-teams#10]
- [__Project__](https://metabuidl.nearspace.info/profile/29)
- __Type__: `newbie` `average`
- __Category__: `undefined` `nft` `games`
- __Location__: `russia-ukraine`
- __Remote__: `yes`
- __Required skills__: `javascript`

Good humor required

**Comment by tonborzenko** [comment]
Hello!
I'm interested in this position, please take a look at [my profile](https://metabuidl.nearspace.info/profile/74) and message me to Telegram: @tonborzenko
