### ISSUE TITLE
Designer

### ISSUE THREAD

**Issue by aroralanuk** [near/metabuidl-teams#20]
- [__Project__](https://metabuidl.nearspace.info/profile/64)
- __Type__: `freelancefull-time`
- __Category__: `nft`
- __Location__: `united-states:any`
- __Remote__: `yes`
- __Required skills__: `design` `art` `near-blockchain` `product`

Need someone to design some stuff.

**Comment by AleksandrKharchencko** [comment]
Hello!
I'm interested in this position, please take a look at [my profile](https://metabuidl.nearspace.info/profile/84) and my GitHub account @AleksandrKharchencko

**Comment by aroralanuk** [comment]
@AleksandrKharchencko We decided to not partake in this hackathon, unfortunately.

**Comment by Korsika95** [comment]
Hello!
I'm interested in this position, please take a look at [my profile](https://metabuidl.nearspace.info/profile/97) and my GitHub account @Korsika95

**Comment by kanzy99** [comment]
Hello!
I'm interested in this position, please take a look at [my profile](https://metabuidl.nearspace.info/profile/100) and my GitHub account @kanzy99
